# Generated by Django 5.2.11 on 2026-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
                ('logo', models.ImageField(upload_to='College_Logo')),
            ],
        ),
    ]
