# Generated by Django 5.2.11 on 2026-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegedb',
            name='cpswd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='collegedb',
            name='cuname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
