# Generated by Django 5.2.11 on 2026-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_collegedb_cpswd_collegedb_cuname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=10)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('dead', models.DateField()),
                ('mode', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('maxS', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('certificate', models.ImageField(upload_to='certificate_templates')),
                ('poster', models.ImageField(upload_to='posters')),
            ],
        ),
    ]
