# Generated by Django 5.2.11 on 2026-02-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0003_eventdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='euname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
