# Generated by Django 5.2.11 on 2026-02-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0004_eventdb_euname'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
