# Generated by Django 5.2.11 on 2026-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0005_eventdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='date_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='date_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='event_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='event_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='name_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='name_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
