# Generated by Django 5.2.11 on 2026-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0006_eventdb_date_x_eventdb_date_y_eventdb_event_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='qr_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdb',
            name='qr_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
