# Generated by Django 5.2.11 on 2026-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0007_eventdb_qr_x_eventdb_qr_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mob', models.IntegerField(max_length=20)),
                ('hod', models.CharField(max_length=50)),
                ('cuname', models.CharField(default='', max_length=50)),
                ('cpswd', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CollegeDb',
        ),
    ]
