# Generated by Django 5.2.11 on 2026-03-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0008_departmentdb_delete_collegedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='mob',
            field=models.IntegerField(),
        ),
    ]
