# Generated by Django 5.2.11 on 2026-03-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0009_alter_departmentdb_mob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdb',
            name='dept',
        ),
    ]
