# Generated by Django 5.2.11 on 2026-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_remove_eventdb_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
