# Generated by Django 5.2.11 on 2026-04-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0011_eventdb_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='conclude',
            field=models.CharField(blank=True, null=True),
        ),
    ]
