# Generated by Django 5.2.11 on 2026-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_eventdb_conclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='mob',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='date_x',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='date_y',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='event_x',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='event_y',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='fee',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='maxS',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='name_x',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='name_y',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='qr_x',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='qr_y',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
