# Generated by Django 5.2.11 on 2026-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0013_alter_departmentdb_mob_alter_eventdb_date_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='cpswd',
            field=models.CharField(default='', max_length=128),
        ),
    ]
