# Generated by Django 5.2.11 on 2026-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=30)),
                ('semail', models.CharField(max_length=50)),
                ('scollege', models.CharField(max_length=100)),
                ('sdept', models.CharField(max_length=50)),
                ('syear', models.CharField(max_length=3)),
                ('smob', models.IntegerField()),
            ],
        ),
    ]
