# Generated by Django 5.2.11 on 2026-03-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='syear',
            field=models.CharField(max_length=10),
        ),
    ]
