# Generated by Django 5.2.11 on 2026-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_registrationdb_syear'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='sattendance',
            field=models.CharField(default='Absent', max_length=20),
        ),
    ]
