# Generated by Django 5.2.11 on 2026-03-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_registrationdb_sattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_qr'),
        ),
    ]
