# Generated by Django 5.2.11 on 2026-03-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_registrationdb_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='Students_Certificates'),
        ),
    ]
