# Generated by Django 5.2.11 on 2026-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_studentdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='student_otp',
            field=models.CharField(default='', max_length=6),
        ),
    ]
