# Generated by Django 5.2.11 on 2026-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_studentdb_student_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='student_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
