# Generated by Django 5.2.11 on 2026-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_registrationdb_logname'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='event_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
