# Generated by Django 5.2.11 on 2026-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_registrationdb_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='pay_status',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
    ]
