# Generated by Django 5.2.11 on 2026-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_registrationdb_fee_registrationdb_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
