# Generated by Django 5.2.11 on 2026-03-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_registrationdb_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='dept_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
