# Generated by Django 5.2.11 on 2026-04-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_registrationdb_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdb',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='commented_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationdb',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
