# Generated by Django 5.2.11 on 2026-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_registrationdb_comment_registrationdb_commented_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
