# Generated by Django 5.2.11 on 2026-04-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_alter_registrationdb_commented_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='fee',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdb',
            name='smob',
            field=models.BigIntegerField(),
        ),
    ]
