# Generated by Django 5.2.11 on 2026-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_alter_registrationdb_fee_alter_registrationdb_smob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdb',
            name='student_pass',
            field=models.CharField(max_length=128),
        ),
    ]
