# Generated by Django 5.2.11 on 2026-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_alter_studentdb_student_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdb',
            name='student_college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='student_dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='student_mob',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdb',
            name='student_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
